# Generated by Django 6.0.5 on 2026-05-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='security_alert',
            field=models.BooleanField(default=False),
        ),
    ]
